name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

permissions:
  contents: read

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
        
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Build Flutter(Web) app
        env:
          SENTRY_DNS: ${{ secrets.SENTRY_DNS }}
        run: flutter build web --release --base-href "/flaavn/"

      - name: Setup Pages
        uses: actions/configure-pages@v4
        # No specific configuration needed if deploying to the root of username.github.io/repo-name
        # or if next.config.js handles basePath correctly.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web

  deploy:
    name: Deploy
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4